### ISSUE TITLE
Getting "response was 'oauth_problem=consumer_key_unknown'" Error

### ISSUE THREAD

**Issue by rakhesha** [lakshmi-kannan/jira-oauth-access-token-generator#2]
I tried running the script on my local where the Jira instance is launched, but i'm keep on getting the below error.

Traceback (most recent call last):
  File "generate_access_token.py", line 30, in <module>
    request_token = oauth.fetch_request_token(REQUEST_TOKEN_URL)
  File "/usr/local/lib/python3.5/dist-packages/requests_oauthlib/oauth1_session.py", line 268, in fetch_request_token
    token = self._fetch_token(url, **request_kwargs)
  File "/usr/local/lib/python3.5/dist-packages/requests_oauthlib/oauth1_session.py", line 351, in _fetch_token
    raise TokenRequestDenied(error % (r.status_code, r.text), r)
requests_oauthlib.oauth1_session.TokenRequestDenied: Token request failed with code 401, response was 'oauth_problem=consumer_key_unknown'.

Can you please mention how to run this file? 

Thanks,

**Comment by sheeeng** [comment]
I have the same error too.
```
Traceback (most recent call last):
  File "generate_access_token.py", line 30, in <module>
    request_token = oauth.fetch_request_token(REQUEST_TOKEN_URL)
  File "/home/leonard/.local/lib/python2.7/site-packages/requests_oauthlib/oauth1_session.py", line 268, in fetch_request_token
    token = self._fetch_token(url, **request_kwargs)
  File "/home/leonard/.local/lib/python2.7/site-packages/requests_oauthlib/oauth1_session.py", line 351, in _fetch_token
    raise TokenRequestDenied(error % (r.status_code, r.text), r)
requests_oauthlib.oauth1_session.TokenRequestDenied: Token request failed with code 401, response was 'oauth_problem=signature_invalid&oauth_signature=......
```

**Comment by sheeeng** [comment]
Check the consumer key is correct with the setup specified in the Jira instance.
```
# The Consumer Key created while setting up the "Incoming Authentication" in
# JIRA for the Application Link.
CONSUMER_KEY = u''  # Modify this line.
```
