### ISSUE TITLE
Getting error net.oauth.OAuthException: java. security.SignatureException: Signature length not correct: got 256 but was expecting 128

### ISSUE THREAD

**Issue by kk12345-png** [lakshmi-kannan/jira-oauth-access-token-generator#3]
While executing this program, I am getting error as follows. Please help.
Traceback (most recent call last):
  File "generate_access_token.py", line 30, in <module>
    request_token = oauth.fetch_request_token(REQUEST_TOKEN_URL)
  File "/home/kedark123/.virtualenvs/my-virtualenv/local/lib/python2.7/site-packages/requests_oauthlib/oauth1_session.py", line 268, in fetc
h_request_token
    token = self._fetch_token(url, **request_kwargs)
  File "/home/kedark123/.virtualenvs/my-virtualenv/local/lib/python2.7/site-packages/requests_oauthlib/oauth1_session.py", line 351, in _fet
ch_token
    raise TokenRequestDenied(error % (r.status_code, r.text), r)
requests_oauthlib.oauth1_session.TokenRequestDenied: Token request failed with code 500, response was '<!DOCTYPE html><html lang="en"><head>
<meta charset="utf-8"><meta http-equiv="X-UA-Compatible" content="IE=edge"><title>Oops - an error has occurred</title><script type="text/jav
ascript">contextPath = "";</script><link type='text/css' rel='stylesheet' href='/static-assets/metal-all.css' media='all'><script src='/stat
ic-assets/metal-all.js'></script><meta name="decorator" content="none" /></head><body class=" error-page error500"><script type="t
ext/javascript">document.body.className += " js-enabled";</script><div id="page"><header id="header" role="banner"></header>
<section id="content" role="main"><div class="aui-page-panel"><div class="aui-page-panel-inner"><section class="aui-page-panel-content lower
Content"><div id="error-state"><span class="error-type"></span><h1>Sorry, we had some technical problems during your last operation.</h1><h2
 class="technical-details-header"><span>Request assistance</span></h2><div id="technical-details-content" class="technical-details js-hidden
"><p>Copy the content below and send it to your JIRA Administrator</p><div class="technical-details-content" contentEditable readonly><h2>Te
chnical details</h2><p class="referral">Log&#39;s referral number: <strong id="log-referral-id">4688496b-e948-4c81-ae29-a858237a6078</strong
></p><div class="info-section" id="causePanel"><h2>Cause</h2><p>Referer URL: <b>Unknown</b></p><pre></pre><p>net.oauth.OAuthException: java.
security.SignatureException: Signature length not correct: got 256 but was expecting 128</p></div></div></div><p>Return to the <a href="java
script:window.history.back()">previous page</a></p></div></section></div></div
></section><footer id="footer" role="contentinfo"><section class="footer-body"><ul class="atlassian
-footer">
    <li>
        Atlassian JIRA <a class="seo-link" rel="nofollow" href="https://www.atlassian.com/software/jira">Project Management Software</a>
                                            <span id="footer-build-information">(v7.5.0#75005-<span title='fd8c849d4e278dd8bbaccc61e707a716a
d697024' data-commit-id='fd8c849d4e278dd8bbaccc61e707a716ad697024}'>sha1:fd8c849</span>:jsd-noxe1231)</span>
    </li>
    <li>
        <a id="about-link" rel="nofollow" href="/secure/AboutPage.jspa/secure/AboutPage.jspa">About JIRA</a>
    </li>

<li>
        <a id="footer-report-problem-link" rel="nofollow" href="/secure/CreateIssue!default.jspa">Report a problem</a>
    </li>
</ul>
    <ul class="atlassian-footer">
        <li class="licensemessage">
            
        </li>
    </ul>
<div id="footer-logo"><a href="http://www.atlassian.com/" rel="nofollow">Atlassian</a></div></section></footer></div></body></html>'.

**Comment by kk12345-png** [comment]
@lakshmi-kannan could you please suggest solution on this
